# This file configures the Dart analyzer to enforce
# consistent, clean, and maintainable Flutter code.

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    dead_code: error
    missing_required_param: error
    missing_return: error

linter:
  rules:
    # ---------- STYLE & READABILITY ----------
    prefer_single_quotes: true
    always_use_package_imports: true
    lines_longer_than_80_chars: false

    # ---------- CODE SAFETY ----------
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true

    # ---------- BEST PRACTICES ----------
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # ---------- PERFORMANCE ----------
    avoid_redundant_argument_values: true
    unnecessary_lambdas: true
    unnecessary_this: true

    # ---------- CLEAN ARCHITECTURE ----------
    depend_on_referenced_packages: true
    prefer_final_locals: true
    prefer_final_fields: true
